url: "https://digitalwriting.github.io"
baseurl: "/eng6800-fall2025-sample-portfolio"
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: T&T Sample Site
description: T&T sample site for intro